import { jsPDF } from "jspdf";
import { amountInWords, monthNames } from "./payroll";

type Item = { component_name: string; component_type: string; amount: number };

export type PayslipData = {
  companyName: string;
  companyAddress: string;
  payslipNumber: string;
  month: number;
  year: number;
  employee: {
    name: string; code: string; designation?: string | null; department?: string | null;
    joining_date?: string | null; pan?: string | null; uan?: string | null;
    bank_name?: string | null; bank_account_number?: string | null;
  };
  items: Item[];
  gross: number;
  totalDeductions: number;
  net: number;
  generatedBy: string;
};

const money = (n: number) => "INR " + new Intl.NumberFormat("en-IN", { maximumFractionDigits: 2 }).format(Number(n) || 0);

export function generatePayslipPdf(d: PayslipData) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const M = 40;

  doc.setFillColor(16, 122, 87);
  doc.rect(0, 0, W, 70, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold").setFontSize(18).text(d.companyName, M, 32);
  doc.setFont("helvetica", "normal").setFontSize(9).text(d.companyAddress, M, 48);
  doc.setFontSize(11).setFont("helvetica", "bold")
    .text(`Payslip — ${monthNames[d.month - 1]} ${d.year}`, W - M, 40, { align: "right" });

  doc.setTextColor(30, 30, 30);
  let y = 96;
  doc.setFontSize(9).setFont("helvetica", "normal");
  const left: [string, string][] = [
    ["Employee Name", d.employee.name],
    ["Employee ID", d.employee.code],
    ["Designation", d.employee.designation ?? "—"],
    ["Department", d.employee.department ?? "—"],
  ];
  const right: [string, string][] = [
    ["Date of Joining", d.employee.joining_date ?? "—"],
    ["PAN", d.employee.pan ?? "—"],
    ["UAN", d.employee.uan ?? "—"],
    ["Bank", `${d.employee.bank_name ?? "—"} ${d.employee.bank_account_number ? "•••• " + d.employee.bank_account_number.slice(-4) : ""}`],
  ];
  left.forEach(([k, v], i) => {
    doc.setTextColor(110).text(`${k}`, M, y + i * 16);
    doc.setTextColor(20).text(String(v), M + 105, y + i * 16);
  });
  right.forEach(([k, v], i) => {
    doc.setTextColor(110).text(`${k}`, W / 2 + 10, y + i * 16);
    doc.setTextColor(20).text(String(v), W / 2 + 110, y + i * 16);
  });

  y += 78;
  doc.setDrawColor(220).line(M, y, W - M, y);
  y += 20;

  const earnings = d.items.filter((i) => i.component_type === "earning");
  const deductions = d.items.filter((i) => i.component_type === "deduction");
  const colW = (W - M * 2) / 2;

  doc.setFont("helvetica", "bold").setFontSize(10).setTextColor(20);
  doc.text("Earnings", M, y);
  doc.text("Deductions", M + colW + 10, y);
  y += 8;
  doc.setDrawColor(230).line(M, y, M + colW - 10, y).line(M + colW + 10, y, W - M, y);

  doc.setFont("helvetica", "normal").setFontSize(9);
  const rows = Math.max(earnings.length, deductions.length);
  for (let i = 0; i < rows; i++) {
    const ry = y + 16 + i * 15;
    const e = earnings[i];
    const de = deductions[i];
    if (e) { doc.text(e.component_name, M, ry); doc.text(money(e.amount), M + colW - 10, ry, { align: "right" }); }
    if (de) { doc.text(de.component_name, M + colW + 10, ry); doc.text(money(de.amount), W - M, ry, { align: "right" }); }
  }
  y = y + 16 + rows * 15 + 6;
  doc.setDrawColor(230).line(M, y, M + colW - 10, y).line(M + colW + 10, y, W - M, y);
  y += 16;
  doc.setFont("helvetica", "bold");
  doc.text("Gross Earnings", M, y); doc.text(money(d.gross), M + colW - 10, y, { align: "right" });
  doc.text("Total Deductions", M + colW + 10, y); doc.text(money(d.totalDeductions), W - M, y, { align: "right" });

  y += 28;
  doc.setFillColor(240, 249, 245).rect(M, y, W - M * 2, 46, "F");
  doc.setFontSize(12).setTextColor(16, 122, 87).text("Net Pay", M + 14, y + 22);
  doc.setFontSize(14).text(money(d.net), W - M - 14, y + 22, { align: "right" });
  doc.setFontSize(8).setTextColor(70).setFont("helvetica", "normal")
    .text(amountInWords(d.net), M + 14, y + 38);

  y += 74;
  doc.setFontSize(8).setTextColor(110);
  doc.text(`Payslip No: ${d.payslipNumber}`, M, y);
  doc.text(`Payroll Period: ${monthNames[d.month - 1]} ${d.year}`, M, y + 12);
  doc.text(`Generated on: ${new Date().toLocaleDateString("en-IN")}`, M, y + 24);
  doc.text(`Generated by: ${d.generatedBy}`, M, y + 36);
  doc.text("This is a computer generated payslip and does not require a signature.", M, y + 58);
  doc.setDrawColor(220).line(M, y + 74, W - M, y + 74);
  doc.text(`${d.companyName} · ${d.companyAddress}`, W / 2, y + 90, { align: "center" });

  doc.save(`Payslip-${d.employee.code}-${d.year}-${String(d.month).padStart(2, "0")}.pdf`);
}
